version: '3.2'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    depends_on:
      - postgres
    env_file: .env
    environment:
      DEBUG: 'true'
    command: bash -c "/tmp/init_db.sh && gunicorn wsgi:application -w 2 -b :8000"

  web-static:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static

volumes:
  web:
  pgdata:
