version: '3.2'
services:
  postgres:
    image: postgres:latest
# Uncomment this line and update to enable different configuration settings
#    command: postgres -c log_min_duration_statement=0
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DB_SERVICE
      - DB_PORT
      - SECRET_KEY

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres

  web:
    restart: always
    build: ./web
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    depends_on:
      - postgres
    command: bash -c "/tmp/init_db.sh && gunicorn wsgi:application -w 2 -b :8000"
    env_file: .env
    environment:
      - DB_SERVICE
      - DB_PORT
      - SECRET_KEY
      # Define this in .env for development mode. DO NOT USED IN PRODUCTION
      - DEBUG

  web-static:
    restart: always
    build: ./nginx/
    env_file: .env
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - /www/static

volumes:
  web:
  pgdata:
